"""embeddings

Revision ID: 4b8121df2658
Revises: 761a9b543d78
Create Date: 2025-12-01 01:29:57.142640

"""
from typing import Sequence, Union

from alembic import op
import pgvector
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4b8121df2658'
down_revision: Union[str, Sequence[str], None] = '761a9b543d78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    op.add_column('products', sa.Column('category_name', sa.String(length=256), nullable=False))
    op.add_column('products', sa.Column('vendor', sa.String(length=128), nullable=False))
    op.add_column('products', sa.Column('type', sa.String(length=128), nullable=True))
    op.add_column('products', sa.Column('parent_id', sa.String(length=64), nullable=True))
    op.add_column('products', sa.Column('parent_name', sa.String(length=128), nullable=True))
    op.add_column('products', sa.Column('weight_kg', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('shipping_weight_kg', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('volume_l', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('length_mm', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('key_params', sa.JSON(), nullable=True))
    op.add_column('products', sa.Column('picture_url', sa.Text(), nullable=False))
    op.add_column('products', sa.Column('url', sa.Text(), nullable=False))
    op.add_column('products', sa.Column('description', sa.Text(), nullable=False))
    op.add_column('products', sa.Column('product_role', sa.String(length=64), nullable=False))
    op.add_column('products', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True))
    op.drop_constraint(op.f('products_external_id_key'), 'products', type_='unique')
    op.drop_column('products', 'external_id')
    op.drop_column('products', 'raw_attributes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP EXTENSION IF EXISTS vector')
    op.add_column('products', sa.Column('raw_attributes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('external_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('products_external_id_key'), 'products', ['external_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('products', 'embedding')
    op.drop_column('products', 'product_role')
    op.drop_column('products', 'description')
    op.drop_column('products', 'url')
    op.drop_column('products', 'picture_url')
    op.drop_column('products', 'key_params')
    op.drop_column('products', 'length_mm')
    op.drop_column('products', 'volume_l')
    op.drop_column('products', 'shipping_weight_kg')
    op.drop_column('products', 'weight_kg')
    op.drop_column('products', 'parent_name')
    op.drop_column('products', 'parent_id')
    op.drop_column('products', 'type')
    op.drop_column('products', 'vendor')
    op.drop_column('products', 'category_name')
    # ### end Alembic commands ###
