"""llm_recomendations

Revision ID: 9040e29ff2b6
Revises: 98f2adf41f4e
Create Date: 2025-12-12 13:46:09.834734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9040e29ff2b6'
down_revision: Union[str, Sequence[str], None] = '98f2adf41f4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_recommendations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('main_product_id', sa.Integer(), nullable=False),
    sa.Column('rec_text', sa.Text(), nullable=False),
    sa.Column('rec_rank', sa.Integer(), nullable=False),
    sa.Column('matched_product_id', sa.Integer(), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('resolved_rank', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['main_product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matched_product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_llm_rec_main', 'llm_recommendations', ['main_product_id'], unique=False)
    op.create_index('idx_llm_rec_matched', 'llm_recommendations', ['matched_product_id'], unique=False)
    op.create_index(op.f('ix_llm_recommendations_main_product_id'), 'llm_recommendations', ['main_product_id'], unique=False)
    op.create_index(op.f('ix_llm_recommendations_matched_product_id'), 'llm_recommendations', ['matched_product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_llm_recommendations_matched_product_id'), table_name='llm_recommendations')
    op.drop_index(op.f('ix_llm_recommendations_main_product_id'), table_name='llm_recommendations')
    op.drop_index('idx_llm_rec_matched', table_name='llm_recommendations')
    op.drop_index('idx_llm_rec_main', table_name='llm_recommendations')
    op.drop_table('llm_recommendations')
    # ### end Alembic commands ###
