"""expert_embedding

Revision ID: 98f2adf41f4e
Revises: b8361e8858de
Create Date: 2025-12-04 15:54:44.636945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '98f2adf41f4e'
down_revision: Union[str, Sequence[str], None] = 'b8361e8858de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('expert_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True))
    op.add_column('products', sa.Column('expert_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'expert_reason')
    op.drop_column('products', 'expert_embedding')
    # ### end Alembic commands ###
