"""armstats

Revision ID: b8361e8858de
Revises: bd61f3d7f753
Create Date: 2025-12-02 21:44:26.347524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8361e8858de'
down_revision: Union[str, Sequence[str], None] = 'bd61f3d7f753'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arm_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('recommended_product_id', sa.Integer(), nullable=False),
    sa.Column('alpha', sa.Float(), nullable=False),
    sa.Column('beta', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recommended_product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'recommended_product_id')
    )
    op.create_index(op.f('ix_arm_stats_id'), 'arm_stats', ['id'], unique=False)
    op.create_index(op.f('ix_arm_stats_product_id'), 'arm_stats', ['product_id'], unique=False)
    op.create_index(op.f('ix_arm_stats_recommended_product_id'), 'arm_stats', ['recommended_product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_arm_stats_recommended_product_id'), table_name='arm_stats')
    op.drop_index(op.f('ix_arm_stats_product_id'), table_name='arm_stats')
    op.drop_index(op.f('ix_arm_stats_id'), table_name='arm_stats')
    op.drop_table('arm_stats')
    # ### end Alembic commands ###
