"""nullable fix

Revision ID: bd61f3d7f753
Revises: 4b8121df2658
Create Date: 2025-12-02 20:30:51.235719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd61f3d7f753'
down_revision: Union[str, Sequence[str], None] = '4b8121df2658'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'vendor',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('products', 'parent_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('products', 'parent_name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('products', 'picture_url',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('products', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('products', 'picture_url',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('products', 'parent_name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('products', 'parent_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('products', 'vendor',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    # ### end Alembic commands ###
